apiVersion: v1
kind: Namespace
metadata:
  name: cilium-gateways
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public
  namespace: cilium-gateways
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
spec:
  gatewayClassName: cilium
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All
  - name: wildcard-sidus-dev-https
    protocol: HTTPS
    port: 443
    hostname: "*.sidus.dev"
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: wildcard-sidus-dev